#!/bin/bash
# NEXTFLOW TASK: output_reads (ggal_liver)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 2 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

function nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /home/dileep/Dropbox/Boston_University/challenge_project/pipeliner/jinja/nextflow_jinja/data/ggal/work/88/3fd2ae5ee5c9cea45054ef67dc879a/.exitcode
  set +u
  [[ "$COUT" ]] && rm -f "$COUT" || true
  [[ "$CERR" ]] && rm -f "$CERR" || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /home/dileep/Dropbox/Boston_University/challenge_project/pipeliner/jinja/nextflow_jinja/data/ggal/work/88/3fd2ae5ee5c9cea45054ef67dc879a/.command.begin
[ -f /home/dileep/Dropbox/Boston_University/challenge_project/pipeliner/jinja/nextflow_jinja/data/ggal/work/88/3fd2ae5ee5c9cea45054ef67dc879a/.command.env ] && source /home/dileep/Dropbox/Boston_University/challenge_project/pipeliner/jinja/nextflow_jinja/data/ggal/work/88/3fd2ae5ee5c9cea45054ef67dc879a/.command.env
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
rm -f ggal_liver_1.fq
rm -f ggal_liver_2.fq
ln -s /home/dileep/Dropbox/Boston_University/challenge_project/pipeliner/jinja/nextflow_jinja/data/ggal/ggal_liver_1.fq ggal_liver_1.fq
ln -s /home/dileep/Dropbox/Boston_University/challenge_project/pipeliner/jinja/nextflow_jinja/data/ggal/ggal_liver_2.fq ggal_liver_2.fq


set +e
COUT=$PWD/.command.po; mkfifo "$COUT"
CERR=$PWD/.command.pe; mkfifo "$CERR"
tee .command.out < "$COUT" &
tee1=$!
tee .command.err < "$CERR" >&2 &
tee2=$!
(
/bin/bash -ue /home/dileep/Dropbox/Boston_University/challenge_project/pipeliner/jinja/nextflow_jinja/data/ggal/work/88/3fd2ae5ee5c9cea45054ef67dc879a/.command.sh
) >"$COUT" 2>"$CERR" &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
